### PR TITLE
feat: intercom-react-native

### PR DESCRIPTION
**Pull request by enagorny**
# Why

Expo support for intercom
[existing](https://github.com/cmaycumber/config-plugin-react-native-intercom) plugin isn't actively maintained and has some [crucial](https://github.com/cmaycumber/config-plugin-react-native-intercom/issues/72) issues 

The original author of the config plugin [suggested](https://github.com/expo/config-plugins/issues/27) previously to have it here. However this code isn't based on the https://github.com/cmaycumber/config-plugin-react-native-intercom .
It is based on the [gist](https://github.com/cmaycumber/config-plugin-react-native-intercom/issues/72#issuecomment-1805773965) by [wcastand](https://github.com/wcastand)

## Limitations
- **No push notifications support**: Intercom push notifications currently aren't supported by this config plugin extension. This will be added in the future.
- **compileSdkVersion: 34**: This plugin requires `compileSdkVersion` to be `34` or higher. This is because the Intercom SDK requires `compileSdkVersion` to be `34` or higher. Check the example how to do this using expo-build-properties.

# How

Created new config plugin

# Test Plan
Tested it locally

### CODE REVIEW

**Comment by yonitou** [comment]
Hi @enagorny 
I'm also waiting for a rebirth of the intercom <-> expo plugin so thanks for starting it :) 
I think many of us are using push notifications with Intercom. 
Do you think that using the code from https://github.com/cmaycumber/config-plugin-react-native-intercom for the notifications could be an idea ?

**Comment by enagorny** [comment]
@yonitou I think it is a good time to review the approach of push notification setup. Since the https://github.com/cmaycumber/config-plugin-react-native-intercom was introduced I believe expo conflig plugins became more powerful and intercom setup instructions might be changed. 
This is still in my TODO list

**Comment by Joshandrews43** [comment]
commenting to show support for this project

**Comment by yonitou** [comment]
+1
When does this PR will be reviewed ? It's really important for the Intercom community

**Comment by GabrielDierks** [comment]
+1

**Comment by GabrielDierks** [comment]
@brentvatne Can you guys please have a look? <3 Intercom is crucial for a lot of expo apps and unfortunately they introduced a lot of important fixes in their latest versions which cannot be accessed by the current unmaintained config plugin. 🙏

**Comment by enagorny** [comment]
I think the expo team might want to postpone this until SDK 50 is released. react-native-intercom 6.* requires `compileSdkVersion: 34` which will be the default in SDK 50. 

Having compileSdkVersion 34 in expo SDK 49 might lead to issues and may require patching some expo packages(we have already done one for the expo-image-loader).

**Comment by brentvatne** [comment]
thank you for this PR! what do you think about opening this directly to https://github.com/intercom/intercom-react-native/pulls? ideally, the config plugin for a library sits alongside it directly so it can stay in sync with releases.

**Comment by erwanlpfr** [comment]
Hello !

I opened a PR in intercom repo.
Let me know if you want to add anything.

https://github.com/intercom/intercom-react-native/pull/155

**Comment by yonitou** [comment]
Hi @brentvatne, 
Looks like Intercom is not very "responsive" atm.

They don't have an issue panel on their Github repository so I don't even know if this is really an _open source_ repository (all the pull requests have been created and merged by Intercom developers). 

I don't have a lot of hope about adding and maintaining the plugin from Intercom repository. Do you think we can add it here ? 

Thanks,

**Comment by yonitou** [comment]
**UPDATE** : Intercom just answered and are looking into the PR !

@enagorny : did you have time to check about push notifications support for this plugin ?

**Comment by Seamus1989** [comment]
commenting for support!

**Comment by yonitou** [comment]
Intercom just merged the PR :) 
I think this thread can be closed because it's not concerning Expo Team anymore.

**Pull request closed without merging**
