### PR TITLE
refactor!: upgrade to Expo SDK 50

### PR DESCRIPTION
**Pull request by byCedric**
# Why

New year, new SDK.

# How

- Ran this for all **apps/***
  - `$ yarn install`
  - `$ yarn expo install "expo@^50.0.2"`
  - `$ yarn expo install --fix`
- Ran a script to bump all peer dependencies on `expo` to `^50` in **packages/***  

# Test Plan

- [ ] ❌ **apps/app**
  Detox is failing yet again.
- [x] ~~**apps/apple-settings**~~
- [x] ~~**apps/ffmpeg-kit-react-native**~~
  Had to update the test video, old one was not hosted anymore.
- [ ] ❌ **apps/ios-stickers**
  This is the failure related to `react_native_post_install` reading the wrong `Info.plist` file, I remember you did something related to this @EvanBacon 
- [x] ~~⚠️ **apps/react-native-ble-plx**~~
  Config plugin has been merged inside `react-native-ble-plx`, swapped it over to test SDK 50, and removed the plugin from this repository.
- [ ] ❌ **apps/react-native-branch**
  Android needs an overhaul, there is more we need to set in `MainActivity` and `MainApplication`. ([docs](https://help.branch.io/developers-hub/docs/react-native#android-1))
- [x] ~~**apps/react-native-dynamic-app-icon**~~
- [x] ~~**apps/react-native-google-cast**~~
  Added support for `MainActivity.kt`, and [added missing `tintColor` for Android](https://react-native-google-cast.github.io/docs/components/CastButton).
- [x] ~~**apps/react-native-pdf**~~
  Had to enable HTTP traffic, since we are loading from `http://`.
- [x] ~~**apps/react-native-quick-actions**~~
- [x] ~~**apps/react-native-siri-shortcut**~~
  There are warnings in the terminal "Unable to simultaneously satisfy constraints." but it seems to work fine.
- [ ] ❌ **apps/react-native-webrtc**
  Currently triggers a Hermes failure on launch. Could be related to their `expo default class X extends Y` usage, which used to be a [Babebl issue](https://github.com/babel/babel/issues/2694).
    - Sidenote, their [example app is still running React Native 0.71](https://github.com/react-native-webrtc/react-native-webrtc/blob/1fc8c29cefa76577d0d6294e571186780b428a98/examples/GumTestApp/package.json#L15)

TBD

### CODE REVIEW

**Comment by byCedric** [comment]
Lmao, thanks yarn...
image

**Comment by fobos531** [comment]
@byCedric 

`react-native-branch` experiences a compilation error on SDK 50, for that I've submitted a minor PR to fix it: https://github.com/expo/config-plugins/pull/216

**Review by oftoapp — APPROVED** [review]

**Comment by fobos531** [comment]
@byCedric 

About `react-native-branch`... are you certain that Android needs additional work? I just checked their setup docs for Android and it looks to be exactly what is already present in the lifecycle listeners implemented here:

https://github.com/expo/config-plugins/blob/main/packages/react-native-branch/android/src/main/java/expo/modules/adapters/branch/BranchReactActivityLifecycleListener.kt

https://github.com/expo/config-plugins/blob/main/packages/react-native-branch/android/src/main/java/expo/modules/adapters/branch/BranchApplicationLifecycleListener.kt

So I'm not sure what else would there need to be adjusted (besides #216)

**Comment by fobos531** [comment]
Some more info about `react-native-webrtc` compatibility and Hermes failure can be seen by tracing the info in this comment: https://github.com/react-native-webrtc/react-native-webrtc/issues/1503#issuecomment-1918947695

**Comment by doug-shontz** [comment]
Any progress on this?

I had the bad luck of trying to convince my new team to use Expo and it turns out the day I tried to have people look at setting up a new project was the day AFTER Expo 50 came out (we were waiting on the Expo Router v3 changes).  We use Google Cast and Detox on our raw RN apps and so their testing started failing almost immediately just for NPM not wanting to install the right packaging (we are not allowed to use legacy deps).

We backpedalled to Expo 49 and was able to get things working, but, since our main interest was in the changes to the Expo router that were released in Expo 50, that made a huge dent in trying to sell Expo's stability to our management.

No shade thrown for this...I understand the complexity.  Just hoping this gets solved soon enough for us to not miss our start window on our new projects!

**Comment by akkilaa** [comment]
@macsint My android's build is failing
image

**Comment by EvanBacon** [comment]
I'll be taking over this upgrade today

**Comment by EvanBacon** [comment]
The webrtc issue is related to their use of `event-target-shim@6` colliding with React Native's usage of `event-target-shim@5`.

**Comment by EvanBacon** [comment]
https://github.com/expo/config-plugins/pull/220

**Pull request closed without merging**
